[pytest]
testpaths = tests
python_files = test_cookies.py
addopts = --browser chromium --browser firefox --browser webkit -n auto -v -s --tb=short

markers = 
    regression: Główny potok testów regresyjnych